name: linguacafedev

networks:
    linguacafedev:
        driver: bridge

services:
    webserver:
        container_name: linguacafe-webserver-dev
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/PhpDockerfileDev
        depends_on:
            mysql:
                condition: service_healthy
        volumes:
            - ./:/var/www/html
            - ./docker/vhost.conf:/etc/apache2/sites-available/000-default.conf
            - ./docker/supervisor-horizon.conf:/etc/supervisor/conf.d/horizon.conf
            - ./docker/supervisor-websockets.conf:/etc/supervisor/conf.d/websockets.conf
        environment:
            PYTHON_CONTAINER_NAME: linguacafe-python-service-dev
            DB_DATABASE: linguacafe-dev
            DB_USERNAME: linguacafe-dev
            DB_PASSWORD: linguacafe-dev
            DB_HOST: linguacafe-database-dev
            DB_PORT: 3306
            BACKUP_INTERVAL: "0,15,30,45 * * * *"
            MAX_SAVED_BACKUPS: 8
        ports:
            - "6001:6001"
            - "3000:3000"
            - "81:80"
        networks:
            - linguacafedev
        extra_hosts:
            - "host.docker.internal:host-gateway"
    mysql:
        image: mysql:8.0
        container_name: linguacafe-database-dev
        restart: unless-stopped
        tty: true
        healthcheck:
            test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$MYSQL_ROOT_PASSWORD']
            interval: 5s
            timeout: 5s
            retries: 10
        ports:
          - "3308:3306"
        volumes:
          - ./docker/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: linguacafe-dev
            MYSQL_USER: linguacafe-dev
            MYSQL_PASSWORD: linguacafe-dev
            MYSQL_ROOT_PASSWORD: linguacafe-dev
            SERVICE_NAME: linguacafe-dev
        networks:
            - linguacafedev
    redis:
        image: redis:7.2-alpine
        container_name: linguacafe-redis-dev
        volumes: 
            - ./cache:/data
        ports:
            - "6379:6379"
        environment:
            REDIS_PASSWORD: linguacafe-dev
            REDIS_PORT: 6379
            REDIS_DATABASES: 16
        networks:
            - linguacafedev
    python:
        container_name: linguacafe-python-service-dev
        command: "python3 /app/tokenizer.py"
        restart: unless-stopped
        tty: true
        ports:
            - "8678:8678"
        build:
            dockerfile: ./docker/PythonDockerfileDev
        volumes:
            - ./tools:/app
            - ./storage/app:/var/www/html/storage/app
        networks:
            - linguacafedev
        environment:
            PYTHONPATH: "/var/www/html/storage/app/model"
